package interfejs.igre;

import osnova.KontrolerIksOks;

/**
 *
 * @author SMRTNIK
 */
public class IksOksGUI extends javax.swing.JFrame {

    public KontrolerIksOks kontroler;
    static public boolean zastavica;

    public IksOksGUI(boolean zastavica) {
        initComponents();
        this.kontroler = new KontrolerIksOks(this);
        this.zastavica = zastavica;
    }

    public static boolean getZastavica() {
        return zastavica;
    }

    public void upozorenje(String poruka) {
        napomena_L.setText(poruka);
        obavestenje_L.setVisible(true);
    }

    public void pokaziSledecegIgraca(int igrac) {
        trenutniIgrac_L.setText(Integer.toString(igrac));
    }

    public void resetPolja() {
        polje1.setText("");
        polje2.setText("");
        polje3.setText("");
        polje4.setText("");
        polje5.setText("");
        polje6.setText("");
        polje7.setText("");
        polje8.setText("");
        polje9.setText("");
        trenutniIgrac_L.setText("1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        obavestenje_L = new javax.swing.JDialog();
        novaigra2_B = new javax.swing.JButton();
        napomena_L = new java.awt.Label();
        ugasi_B = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        polje5 = new java.awt.Label();
        polje1 = new java.awt.Label();
        polje2 = new java.awt.Label();
        polje3 = new java.awt.Label();
        polje8 = new java.awt.Label();
        polje9 = new java.awt.Label();
        polje6 = new java.awt.Label();
        polje7 = new java.awt.Label();
        polje4 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        trenutniIgrac_L = new javax.swing.JLabel();
        izlaz_B = new javax.swing.JButton();
        novaIgra_B = new javax.swing.JButton();

        obavestenje_L.setTitle("Obavestenje");
        obavestenje_L.setAlwaysOnTop(true);
        obavestenje_L.setForeground(java.awt.Color.gray);
        obavestenje_L.setLocation(new java.awt.Point(50, 50));
        obavestenje_L.setName("caixaAlerta"); // NOI18N
        obavestenje_L.setResizable(false);
        obavestenje_L.setSize(new java.awt.Dimension(350, 250));
        obavestenje_L.setType(java.awt.Window.Type.POPUP);

        novaigra2_B.setText("Nova igra");
        novaigra2_B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                novaigra2_BMousePressed(evt);
            }
        });
        novaigra2_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaigra2_BActionPerformed(evt);
            }
        });

        napomena_L.setAlignment(java.awt.Label.CENTER);
        napomena_L.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        napomena_L.setName(""); // NOI18N
        napomena_L.setText("Obavestenje");

        ugasi_B.setText("Izlaz");
        ugasi_B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ugasi_BMousePressed(evt);
            }
        });
        ugasi_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugasi_BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout obavestenje_LLayout = new javax.swing.GroupLayout(obavestenje_L.getContentPane());
        obavestenje_L.getContentPane().setLayout(obavestenje_LLayout);
        obavestenje_LLayout.setHorizontalGroup(
            obavestenje_LLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obavestenje_LLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(novaigra2_B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(ugasi_B)
                .addGap(63, 63, 63))
            .addComponent(napomena_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        obavestenje_LLayout.setVerticalGroup(
            obavestenje_LLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obavestenje_LLayout.createSequentialGroup()
                .addComponent(napomena_L, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(obavestenje_LLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novaigra2_B)
                    .addComponent(ugasi_B))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Igra iks-oks sistema elektrosne biblioteke - SEB");
        setResizable(false);

        label1.setText("Igrac 1 - X");

        label2.setText("Igrac 2 - O");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setAlignmentX(0.6F);
        jSeparator1.setAlignmentY(0.6F);
        jSeparator1.setAutoscrolls(true);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator1.setName(""); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setAlignmentX(0.6F);
        jSeparator2.setAlignmentY(0.6F);
        jSeparator2.setAutoscrolls(true);
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSeparator2.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator2.setName(""); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.6F);
        jSeparator3.setAlignmentY(0.6F);
        jSeparator3.setAutoscrolls(true);
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSeparator3.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator3.setName(""); // NOI18N
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setAlignmentX(0.6F);
        jSeparator4.setAlignmentY(0.6F);
        jSeparator4.setAutoscrolls(true);
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSeparator4.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator4.setName(""); // NOI18N
        jSeparator4.setPreferredSize(new java.awt.Dimension(50, 20));

        polje5.setAlignment(java.awt.Label.CENTER);
        polje5.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        polje5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                polje5MousePressed(evt);
            }
        });

        polje1.setAlignment(java.awt.Label.CENTER);
        polje1.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        polje1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                polje1MousePressed(evt);
            }
        });

        polje2.setAlignment(java.awt.Label.CENTER);
        polje2.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        polje2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                polje2MousePressed(evt);
            }
        });

        polje3.setAlignment(java.awt.Label.CENTER);
        polje3.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        polje3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                polje3MousePressed(evt);
            }
        });

        polje8.setAlignment(java.awt.Label.CENTER);
        polje8.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        polje8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                polje8MousePressed(evt);
            }
        });

        polje9.setAlignment(java.awt.Label.CENTER);
        polje9.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        polje9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                polje9MousePressed(evt);
            }
        });

        polje6.setAlignment(java.awt.Label.CENTER);
        polje6.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        polje6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                polje6MousePressed(evt);
            }
        });

        polje7.setAlignment(java.awt.Label.CENTER);
        polje7.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        polje7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                polje7MousePressed(evt);
            }
        });

        polje4.setAlignment(java.awt.Label.CENTER);
        polje4.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        polje4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                polje4MousePressed(evt);
            }
        });

        jLabel1.setText("Sada je na redu igrac:");

        trenutniIgrac_L.setText("1");

        izlaz_B.setText("Izlaz");
        izlaz_B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                izlaz_BMousePressed(evt);
            }
        });
        izlaz_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izlaz_BActionPerformed(evt);
            }
        });

        novaIgra_B.setText("Nova igra");
        novaIgra_B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                novaIgra_BMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(polje3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(polje6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23)
                                    .addComponent(polje9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(polje2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(polje5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23)
                                    .addComponent(polje8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(polje7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(polje1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(polje4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(trenutniIgrac_L, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(izlaz_B)
                                .addGap(54, 54, 54))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(novaIgra_B)
                                .addGap(30, 30, 30))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(293, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(268, 268, 268)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(174, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trenutniIgrac_L))
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(izlaz_B)
                        .addGap(18, 18, 18)
                        .addComponent(novaIgra_B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(polje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(polje4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(polje7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(polje8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(polje5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(polje2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(polje6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(polje9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(polje3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(97, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(96, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void polje5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polje5MousePressed
        izvrsi(new int[]{1,1,5});
    }//GEN-LAST:event_polje5MousePressed

    private void polje1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polje1MousePressed
        izvrsi(new int[]{0,0,1});
    }//GEN-LAST:event_polje1MousePressed

    private void polje2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polje2MousePressed
        izvrsi(new int[]{1,0,2});
    }//GEN-LAST:event_polje2MousePressed

    private void polje3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polje3MousePressed
        izvrsi(new int[]{2,0,3});
    }//GEN-LAST:event_polje3MousePressed

    private void polje4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polje4MousePressed
        izvrsi(new int[]{0,1,4});
    }//GEN-LAST:event_polje4MousePressed

    private void polje6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polje6MousePressed
        izvrsi(new int[]{2,1,6});
    }//GEN-LAST:event_polje6MousePressed

    private void polje7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polje7MousePressed
        izvrsi(new int[]{0,2,7});
    }//GEN-LAST:event_polje7MousePressed

    private void polje8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polje8MousePressed
        izvrsi(new int[]{1,2,8});
    }//GEN-LAST:event_polje8MousePressed

    private void polje9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polje9MousePressed
        izvrsi(new int[]{2,2,9});
    }//GEN-LAST:event_polje9MousePressed

    private void novaigra2_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaigra2_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novaigra2_BActionPerformed

    private void novaigra2_BMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novaigra2_BMousePressed
        this.kontroler.novaIgra();
        this.resetPolja();
        obavestenje_L.setVisible(false);
    }//GEN-LAST:event_novaigra2_BMousePressed

    private void ugasi_BMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ugasi_BMousePressed
        this.setVisible(false);
    }//GEN-LAST:event_ugasi_BMousePressed

    private void izlaz_BMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izlaz_BMousePressed
        this.setVisible(false);
    }//GEN-LAST:event_izlaz_BMousePressed

    private void novaIgra_BMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novaIgra_BMousePressed
        this.kontroler.novaIgra();
        this.resetPolja();
    }//GEN-LAST:event_novaIgra_BMousePressed

    private void ugasi_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugasi_BActionPerformed
        obavestenje_L.setVisible(false);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ugasi_BActionPerformed

    private void izlaz_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izlaz_BActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_izlaz_BActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IksOksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IksOksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IksOksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IksOksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    private void izvrsi(int[] niz) {
        int igrac = this.kontroler.oznaciti(niz[0], niz[1]);
        switch (niz[2]) {
            case 1:
                if (igrac == 1) {
                    polje1.setText("X");
                } else if (igrac == 2) {
                    polje1.setText("O");
                }
                break;
            case 2:
                if (igrac == 1) {
                    polje2.setText("X");
                } else if (igrac == 2) {
                    polje2.setText("O");
                }
                break;
            case 3:
                if (igrac == 1) {
                    polje3.setText("X");
                } else if (igrac == 2) {
                    polje3.setText("O");
                }
                break;
            case 4:
                if (igrac == 1) {
                    polje4.setText("X");
                } else if (igrac == 2) {
                    polje4.setText("O");
                }
                break;
            case 5:
                if (igrac == 1) {
                    polje5.setText("X");
                } else if (igrac == 2) {
                    polje5.setText("O");
                }
                break;
            case 6:
                if (igrac == 1) {
                    polje6.setText("X");
                } else if (igrac == 2) {
                    polje6.setText("O");
                }
                break;
            case 7:
                if (igrac == 1) {
                    polje7.setText("X");
                } else if (igrac == 2) {
                    polje7.setText("O");
                }
                break;
            case 8:
                if (igrac == 1) {
                    polje8.setText("X");
                } else if (igrac == 2) {
                    polje8.setText("O");
                }
                break;
            case 9:
                if (igrac == 1) {
                    polje9.setText("X");
                } else if (igrac == 2) {
                    polje9.setText("O");
                }
                break;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton izlaz_B;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label napomena_L;
    private javax.swing.JButton novaIgra_B;
    private javax.swing.JButton novaigra2_B;
    private javax.swing.JDialog obavestenje_L;
    private java.awt.Label polje1;
    private java.awt.Label polje2;
    private java.awt.Label polje3;
    private java.awt.Label polje4;
    private java.awt.Label polje5;
    private java.awt.Label polje6;
    private java.awt.Label polje7;
    private java.awt.Label polje8;
    private java.awt.Label polje9;
    private javax.swing.JLabel trenutniIgrac_L;
    private javax.swing.JButton ugasi_B;
    // End of variables declaration//GEN-END:variables
}
